USE `village-management`;

-- LARGE DATA SEED

INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (100, 'G1-M-Joshi', 'male', '1947-09-17', 'Joshi', 'Teacher', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (101, 'G1-F-Joshi', 'female', '1949-01-07', 'Joshi', 'Lawyer', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (102, 'G2-C1-Joshi', 'female', '1979-01-06', 'Joshi', 'Lawyer', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (103, 'G2-S1-Joshi', 'male', '1980-10-01', 'Joshi', 'Teacher', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (104, 'G3-GC11-Joshi', 'male', '2006-10-14', 'Joshi', 'Teacher', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (105, 'G2-C2-Joshi', 'male', '1975-09-16', 'Joshi', 'Teacher', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (106, 'G2-S2-Joshi', 'female', '1976-05-18', 'Joshi', 'Business Owner', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (107, 'G3-GC21-Joshi', 'female', '2007-01-03', 'Joshi', 'Artist', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (108, 'G3-GC22-Joshi', 'male', '2000-01-10', 'Joshi', 'Farmer', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (109, 'G1-M-Verma', 'male', '1950-03-11', 'Verma', 'Farmer', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (110, 'G1-F-Verma', 'female', '1948-03-31', 'Verma', 'Artist', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (111, 'G2-C1-Verma', 'male', '1974-02-26', 'Verma', 'Artist', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (112, 'G2-S1-Verma', 'female', '1980-07-03', 'Verma', 'Doctor', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (113, 'G3-GC11-Verma', 'female', '2009-01-08', 'Verma', 'Teacher', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (114, 'G2-C2-Verma', 'female', '1971-05-22', 'Verma', 'Lawyer', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (115, 'G2-S2-Verma', 'male', '1980-02-13', 'Verma', 'Business Owner', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (116, 'G3-GC21-Verma', 'female', '2000-01-11', 'Verma', 'Scientist', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (117, 'G2-C3-Verma', 'male', '1974-05-09', 'Verma', 'Artist', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (118, 'G2-S3-Verma', 'female', '1976-08-29', 'Verma', 'Teacher', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (119, 'G3-GC31-Verma', 'male', '2003-10-15', 'Verma', 'Engineer', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (120, 'G1-M-Reddy', 'male', '1941-03-07', 'Reddy', 'Doctor', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (121, 'G1-F-Reddy', 'female', '1950-06-12', 'Reddy', 'Farmer', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (122, 'G2-C1-Reddy', 'female', '1970-08-01', 'Reddy', 'Scientist', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (123, 'G2-S1-Reddy', 'male', '1980-11-23', 'Reddy', 'Business Owner', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (124, 'G3-GC11-Reddy', 'female', '2004-02-12', 'Reddy', 'Doctor', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (125, 'G2-C2-Reddy', 'male', '1978-06-10', 'Reddy', 'Lawyer', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (126, 'G2-S2-Reddy', 'female', '1972-03-08', 'Reddy', 'Scientist', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (127, 'G3-GC21-Reddy', 'female', '2005-07-31', 'Reddy', 'Pilot', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (128, 'G3-GC22-Reddy', 'male', '2008-01-30', 'Reddy', 'Lawyer', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (129, 'G2-C3-Reddy', 'female', '1970-06-20', 'Reddy', 'Lawyer', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (130, 'G2-S3-Reddy', 'male', '1980-01-20', 'Reddy', 'Engineer', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (131, 'G3-GC31-Reddy', 'female', '2004-07-07', 'Reddy', 'Chef', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (132, 'G1-M-Nair', 'male', '1940-01-01', 'Nair', 'Lawyer', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (133, 'G1-F-Nair', 'female', '1948-06-03', 'Nair', 'Doctor', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (134, 'G2-C1-Nair', 'female', '1978-03-19', 'Nair', 'Teacher', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (135, 'G2-S1-Nair', 'male', '1973-08-13', 'Nair', 'Chef', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (136, 'G3-GC11-Nair', 'male', '2000-04-04', 'Nair', 'Teacher', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (137, 'G3-GC12-Nair', 'female', '2005-04-16', 'Nair', 'Teacher', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (138, 'G2-C2-Nair', 'female', '1975-05-09', 'Nair', 'Chef', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (139, 'G2-S2-Nair', 'male', '1973-07-31', 'Nair', 'Scientist', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (140, 'G3-GC21-Nair', 'male', '2006-07-11', 'Nair', 'Scientist', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (141, 'G2-C3-Nair', 'female', '1971-03-28', 'Nair', 'Engineer', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (142, 'G2-S3-Nair', 'male', '1972-02-04', 'Nair', 'Farmer', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (143, 'G3-GC31-Nair', 'male', '2004-03-31', 'Nair', 'Lawyer', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (144, 'G3-GC32-Nair', 'male', '2003-07-07', 'Nair', 'Scientist', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (145, 'G1-M-Iyer', 'male', '1944-08-26', 'Iyer', 'Teacher', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (146, 'G1-F-Iyer', 'female', '1951-06-24', 'Iyer', 'Farmer', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (147, 'G2-C1-Iyer', 'male', '1971-10-25', 'Iyer', 'Teacher', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (148, 'G2-S1-Iyer', 'female', '1974-02-23', 'Iyer', 'Lawyer', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (149, 'G3-GC11-Iyer', 'female', '2002-08-11', 'Iyer', 'Pilot', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (150, 'G3-GC12-Iyer', 'female', '2002-07-05', 'Iyer', 'Lawyer', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (151, 'G2-C2-Iyer', 'female', '1972-08-04', 'Iyer', 'Teacher', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (152, 'G2-S2-Iyer', 'male', '1973-09-13', 'Iyer', 'Lawyer', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (153, 'G3-GC21-Iyer', 'female', '2006-01-13', 'Iyer', 'Doctor', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (154, 'G2-C3-Iyer', 'male', '1974-08-29', 'Iyer', 'Scientist', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (155, 'G2-S3-Iyer', 'female', '1972-08-13', 'Iyer', 'Doctor', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (156, 'G3-GC31-Iyer', 'female', '2008-07-16', 'Iyer', 'Pilot', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (157, 'G3-GC32-Iyer', 'male', '2002-01-04', 'Iyer', 'Scientist', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (158, 'G1-M-Deshmukh', 'male', '1942-11-20', 'Deshmukh', 'Engineer', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (159, 'G1-F-Deshmukh', 'female', '1955-02-15', 'Deshmukh', 'Lawyer', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (160, 'G2-C1-Deshmukh', 'male', '1974-12-20', 'Deshmukh', 'Business Owner', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (161, 'G2-S1-Deshmukh', 'female', '1982-09-02', 'Deshmukh', 'Business Owner', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (162, 'G3-GC11-Deshmukh', 'male', '2010-10-04', 'Deshmukh', 'Business Owner', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (163, 'G3-GC12-Deshmukh', 'female', '2003-04-02', 'Deshmukh', 'Business Owner', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (164, 'G2-C2-Deshmukh', 'female', '1980-05-04', 'Deshmukh', 'Engineer', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (165, 'G2-S2-Deshmukh', 'male', '1976-03-10', 'Deshmukh', 'Engineer', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (166, 'G3-GC21-Deshmukh', 'female', '2007-05-10', 'Deshmukh', 'Teacher', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (167, 'G1-M-Choudhury', 'male', '1942-01-02', 'Choudhury', 'Teacher', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (168, 'G1-F-Choudhury', 'female', '1952-06-14', 'Choudhury', 'Doctor', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (169, 'G2-C1-Choudhury', 'female', '1970-02-16', 'Choudhury', 'Doctor', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (170, 'G2-S1-Choudhury', 'male', '1980-09-10', 'Choudhury', 'Pilot', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (171, 'G3-GC11-Choudhury', 'male', '2003-04-02', 'Choudhury', 'Business Owner', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (172, 'G2-C2-Choudhury', 'female', '1973-06-27', 'Choudhury', 'Business Owner', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (173, 'G2-S2-Choudhury', 'male', '1974-09-04', 'Choudhury', 'Pilot', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (174, 'G3-GC21-Choudhury', 'male', '2010-08-06', 'Choudhury', 'Teacher', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (175, 'G3-GC22-Choudhury', 'male', '2008-09-13', 'Choudhury', 'Business Owner', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (176, 'G2-C3-Choudhury', 'male', '1972-03-13', 'Choudhury', 'Scientist', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (177, 'G2-S3-Choudhury', 'female', '1975-07-11', 'Choudhury', 'Farmer', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (178, 'G3-GC31-Choudhury', 'female', '2003-12-04', 'Choudhury', 'Scientist', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (179, 'G1-M-Bose', 'male', '1948-12-20', 'Bose', 'Lawyer', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (180, 'G1-F-Bose', 'female', '1955-09-18', 'Bose', 'Business Owner', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (181, 'G2-C1-Bose', 'male', '1980-02-17', 'Bose', 'Scientist', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (182, 'G2-S1-Bose', 'female', '1976-03-14', 'Bose', 'Teacher', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (183, 'G3-GC11-Bose', 'male', '2002-02-15', 'Bose', 'Teacher', 'A dedicated community worker.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (184, 'G2-C2-Bose', 'male', '1976-02-01', 'Bose', 'Scientist', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (185, 'G2-S2-Bose', 'female', '1980-04-01', 'Bose', 'Farmer', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (186, 'G3-GC21-Bose', 'male', '2000-07-24', 'Bose', 'Business Owner', 'Loves to travel and explore new cultures.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (187, 'G1-M-Malhotra', 'male', '1946-01-25', 'Malhotra', 'Pilot', 'Enjoys gardening and spending time with family.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (188, 'G1-F-Malhotra', 'female', '1954-07-04', 'Malhotra', 'Business Owner', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (189, 'G2-C1-Malhotra', 'male', '1976-10-16', 'Malhotra', 'Artist', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (190, 'G2-S1-Malhotra', 'female', '1982-08-04', 'Malhotra', 'Chef', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (191, 'G3-GC11-Malhotra', 'male', '2002-11-01', 'Malhotra', 'Teacher', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (192, 'G2-C2-Malhotra', 'female', '1979-03-20', 'Malhotra', 'Scientist', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (193, 'G2-S2-Malhotra', 'male', '1974-04-27', 'Malhotra', 'Pilot', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (194, 'G3-GC21-Malhotra', 'male', '2004-05-18', 'Malhotra', 'Lawyer', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (195, 'G2-C3-Malhotra', 'female', '1973-11-05', 'Malhotra', 'Engineer', 'Dedicated to village development.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (196, 'G2-S3-Malhotra', 'male', '1978-05-21', 'Malhotra', 'Doctor', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (197, 'G3-GC31-Malhotra', 'male', '2003-11-06', 'Malhotra', 'Business Owner', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (198, 'G1-M-Kapoor', 'male', '1948-06-20', 'Kapoor', 'Pilot', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (199, 'G1-F-Kapoor', 'female', '1953-09-26', 'Kapoor', 'Artist', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (200, 'G2-C1-Kapoor', 'male', '1979-06-18', 'Kapoor', 'Chef', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (201, 'G2-S1-Kapoor', 'female', '1980-06-15', 'Kapoor', 'Artist', 'Passionate about sustainable living.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (202, 'G3-GC11-Kapoor', 'male', '2004-09-06', 'Kapoor', 'Farmer', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (203, 'G3-GC12-Kapoor', 'female', '2007-07-18', 'Kapoor', 'Scientist', 'Always ready for a new challenge.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (204, 'G2-C2-Kapoor', 'male', '1980-12-28', 'Kapoor', 'Business Owner', 'Interested in modern technology.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (205, 'G2-S2-Kapoor', 'female', '1980-10-31', 'Kapoor', 'Scientist', 'Loves cooking traditional meals.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (206, 'G3-GC21-Kapoor', 'male', '2007-01-19', 'Kapoor', 'Lawyer', 'A great storyteller and humorist.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (207, 'G3-GC22-Kapoor', 'male', '2002-02-09', 'Kapoor', 'Engineer', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (208, 'G2-C3-Kapoor', 'male', '1974-03-05', 'Kapoor', 'Lawyer', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (209, 'G2-S3-Kapoor', 'female', '1982-12-13', 'Kapoor', 'Artist', 'An avid reader and history buff.');
INSERT INTO people (id, name, gender, birth_date, family_name, occupation, bio) VALUES (210, 'G3-GC31-Kapoor', 'male', '2006-11-29', 'Kapoor', 'Pilot', 'An avid reader and history buff.');

INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (100, 101, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (101, 100, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (100, 102, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (101, 102, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (102, 103, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (103, 102, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (102, 104, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (103, 104, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (100, 105, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (101, 105, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (105, 106, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (106, 105, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (105, 107, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (106, 107, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (105, 108, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (106, 108, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (109, 110, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (110, 109, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (109, 111, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (110, 111, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (111, 112, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (112, 111, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (111, 113, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (112, 113, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (109, 114, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (110, 114, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (114, 115, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (115, 114, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (114, 116, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (115, 116, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (109, 117, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (110, 117, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (117, 118, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (118, 117, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (117, 119, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (118, 119, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (120, 121, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (121, 120, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (120, 122, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (121, 122, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (122, 123, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (123, 122, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (122, 124, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (123, 124, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (120, 125, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (121, 125, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (125, 126, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (126, 125, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (125, 127, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (126, 127, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (125, 128, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (126, 128, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (120, 129, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (121, 129, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (129, 130, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (130, 129, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (129, 131, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (130, 131, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (132, 133, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (133, 132, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (132, 134, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (133, 134, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (134, 135, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (135, 134, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (134, 136, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (135, 136, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (134, 137, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (135, 137, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (132, 138, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (133, 138, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (138, 139, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (139, 138, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (138, 140, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (139, 140, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (132, 141, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (133, 141, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (141, 142, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (142, 141, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (141, 143, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (142, 143, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (141, 144, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (142, 144, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (145, 146, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (146, 145, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (145, 147, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (146, 147, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (147, 148, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (148, 147, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (147, 149, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (148, 149, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (147, 150, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (148, 150, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (145, 151, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (146, 151, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (151, 152, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (152, 151, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (151, 153, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (152, 153, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (145, 154, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (146, 154, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (154, 155, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (155, 154, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (154, 156, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (155, 156, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (154, 157, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (155, 157, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (158, 159, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (159, 158, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (158, 160, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (159, 160, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (160, 161, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (161, 160, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (160, 162, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (161, 162, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (160, 163, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (161, 163, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (158, 164, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (159, 164, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (164, 165, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (165, 164, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (164, 166, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (165, 166, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (167, 168, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (168, 167, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (167, 169, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (168, 169, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (169, 170, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (170, 169, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (169, 171, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (170, 171, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (167, 172, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (168, 172, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (172, 173, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (173, 172, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (172, 174, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (173, 174, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (172, 175, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (173, 175, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (167, 176, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (168, 176, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (176, 177, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (177, 176, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (176, 178, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (177, 178, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (179, 180, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (180, 179, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (179, 181, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (180, 181, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (181, 182, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (182, 181, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (181, 183, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (182, 183, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (179, 184, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (180, 184, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (184, 185, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (185, 184, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (184, 186, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (185, 186, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (187, 188, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (188, 187, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (187, 189, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (188, 189, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (189, 190, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (190, 189, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (189, 191, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (190, 191, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (187, 192, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (188, 192, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (192, 193, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (193, 192, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (192, 194, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (193, 194, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (187, 195, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (188, 195, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (195, 196, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (196, 195, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (195, 197, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (196, 197, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (198, 199, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (199, 198, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (198, 200, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (199, 200, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (200, 201, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (201, 200, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (200, 202, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (201, 202, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (200, 203, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (201, 203, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (198, 204, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (199, 204, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (204, 205, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (205, 204, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (204, 206, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (205, 206, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (204, 207, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (205, 207, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (198, 208, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (199, 208, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (208, 209, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (209, 208, 'spouse');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (208, 210, 'child');
INSERT INTO relationships (person_id, related_person_id, relationship_type) VALUES (209, 210, 'child');
